### ISSUE TITLE
make Audio sliders reactive to changes 

### ISSUE THREAD

**Issue by pistolPeterson** [Glue-N-Wrench/GMTK2024#84]
see if theres a way to make audio sliders work as the slider value is changed, for player to have more intuitive controls of audio

**Comment by SnageTheSnakeMage** [comment]
I kinda started on this but ill let you take the wheel.
currently I have it so whenever the value is changed at all it plays a sound. which has some problems as the sound it plays isn't linked to the value of the slider, and it plays the sound like 100x because of how granular a change can be.

The changes have been made in the Options Menu Scene so they affect the options in both the main level and main menu.

ive attached the branch of which i have made these changes to this issue
